#!/bin/bash
if [ $# -eq 0 ];then
  echo 'Usage: /root/batchusers <userfile>'
  exit 1
fi
if [ ! -f $1 ];then
  echo "Input file not found"
  exit 2
fi
for user in `cat $1`
do
  useradd -s /bin/false $user
done

