---
- name: install mariadb and use it
  hosts: server0
  tasks:
    - name: install mariadb-server mariadb
      yum:
        name: mariadb-server,mariadb
        state: latest
    - name: skip networking
      lineinfile:
        path: /etc/my.cnf
        insertafter: 'mysqld]$'
        line: 'skip-networking'
    - name: start and enabled mariadb
      service:
        name: mariadb
        state: started
        enabled: true
