---
- name: secure http in server0
  hosts: server0
  tasks:
    - name: download mod_ssl
      yum: 
        name: mod_ssl
        state: latest
    - name: wget server0.crt
      uri:
        url: 'http://classroom/pub/tls/certs/server0.crt'
        dest: /etc/pki/tls/certs/server0.crt
        force: yes
    - name: wget example-ca.crt
      uri:
        url: 'http://classroom/pub/example-ca.crt'
        dest: /etc/pki/tls/certs/example-ca.crt
        force: yes
    - name: wget server0.key 
      uri:
        url: 'http://classroom/pub/tls/private/server0.key'
        dest: /etc/pki/tls/private/server0.key
        force: yes
    - name: cp ssl to /etc/httpd/conf.d/ssl.conf
      copy:
        src: conf/ssl.conf
        dest: /etc/httpd/conf.d/ssl.conf
        force: yes
    - name: restart and enable httpd
      service:
        name: httpd
        state: restarted
        enabled: true
